// Generated by scripts/generate_ffi_bindings.py; do not edit.
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace ArkTrace.Native;
public static unsafe partial class NativeMethods
{
    public const uint ABI_VERSION = 1;
    public const string CONTRACT_DIGEST = "39b9981a74b3bf293319231fbbccad890e930e4f14f2aa1b6e5703370799cd6b";
    public const uint STATUS_OK = 0;
    public const uint STATUS_BUSY = 1;
    public const uint STATUS_CAPACITY = 2;
    public const uint STATUS_INVALID_INPUT = 3;
    public const uint STATUS_INVALID_BUFFER = 4;
    public const uint STATUS_INVALID_HANDLE = 5;
    public const uint STATUS_ABI_MISMATCH = 6;
    public const uint STATUS_UNSUPPORTED_HOST = 7;
    public const uint STATUS_CLOSED = 8;
    public const uint STATUS_CANCELLED = 9;
    public const uint STATUS_INTERNAL = 10;
    public const uint STATUS_UNSUPPORTED_OPERATION = 11;
    public const uint STATUS_OUTPUT_LIMIT = 12;
    public const uint STATUS_POISONED = 13;
    public const uint CAP_MACOS_ENGINE = 1;
    public const uint CAP_COLD_JSON = 2;
    public const uint CAP_VIEWPORT_RECORDS = 4;
    public const uint CAP_DEVELOPMENT_FIXTURES = 8;
    public const uint RESULT_SUCCESS = 0;
    public const uint RESULT_FAILURE = 1;
    public const uint REQUEST_QUEUED = 1;
    public const uint REQUEST_RUNNING = 2;
    public const uint REQUEST_CANCELLING = 3;
    public const uint REQUEST_SUCCEEDED = 4;
    public const uint REQUEST_FAILED = 5;
    public const uint SESSION_OPENING = 1;
    public const uint SESSION_READY = 2;
    public const uint SESSION_CANCELLING = 3;
    public const uint SESSION_CLOSING = 4;
    public const uint SESSION_FAILED = 5;
    public const uint SESSION_CLOSED = 6;
    public const uint DRAIN_RUNNING = 1;
    public const uint DRAIN_DRAINING = 2;
    public const uint DRAIN_DRAINED = 3;
    public const uint PRIMITIVE_DETAIL = 1;
    public const uint PRIMITIVE_DENSITY = 2;
    public const uint FLAG_VISIBLE = 1;
    public const uint FLAG_FRAME = 2;
    public const uint FLAG_OPEN_ENDED = 4;
    public const uint FLAG_OCCUPANCY = 8;
    public const uint FLAG_UTILIZATION = 16;
    public const uint TRACK_COLLAPSED = 1;
    public const uint TRACK_NESTED = 2;
    public const uint TRACK_OWNER = 4;
    public const uint QUALITY_SCOPE = 1;
    public const uint QUALITY_COUNT = 2;
    public const uint MAXIMUM_ENGINES = 8;
    public const uint MAXIMUM_RESULT_OWNERS = 256;
    public const uint MAXIMUM_CONFIG_BYTES = 16384;
    public const uint MAXIMUM_REQUEST_BYTES = 1048576;
    public const uint MAXIMUM_PATH_BYTES = 4096;
    public const uint CODE_INVALID_ARGUMENT = 1;
    public const uint CODE_TRACE_FILE_NOT_FOUND = 2;
    public const uint CODE_TRACE_FILE_UNREADABLE = 3;
    public const uint CODE_TRACE_FORMAT_UNSUPPORTED = 4;
    public const uint CODE_TRACE_STREAMER_UNAVAILABLE = 5;
    public const uint CODE_TRACE_STREAMER_IDENTITY_MISMATCH = 6;
    public const uint CODE_TRACE_PARSE_FAILED = 7;
    public const uint CODE_TRACE_SCHEMA_UNSUPPORTED = 8;
    public const uint CODE_TRACE_DATABASE_INVALID = 9;
    public const uint CODE_TRACE_CACHE_CORRUPT = 10;
    public const uint CODE_QUERY_FAILED = 11;
    public const uint CODE_QUERY_TIMEOUT = 12;
    public const uint CODE_QUERY_LIMIT_EXCEEDED = 13;
    public const uint CODE_OUTPUT_LIMIT_EXCEEDED = 14;
    public const uint CODE_ANALYSIS_UNSUPPORTED = 15;
    public const uint CODE_CANCELLED = 16;
    public const uint CODE_INTERNAL_ERROR = 17;
    public const uint STAGE_REQUEST = 1;
    public const uint STAGE_PREPARING = 2;
    public const uint STAGE_HASHING = 3;
    public const uint STAGE_CACHE_LOOKUP = 4;
    public const uint STAGE_PARSING = 5;
    public const uint STAGE_VALIDATING = 6;
    public const uint STAGE_INDEXING = 7;
    public const uint STAGE_OPENING_DATABASE = 8;
    public const uint STAGE_QUERYING = 9;
    public const uint STAGE_ANALYZING = 10;
    public const uint STAGE_ENCODING = 11;
    public const uint SOURCE_CPU = 1;
    public const uint SOURCE_THREAD_STATE = 2;
    public const uint SOURCE_NAMED_SLICE = 3;
    public const uint SOURCE_CPU_COUNTER = 4;
    public const uint SOURCE_PROCESS_COUNTER = 5;
    public const uint SOURCE_FRAME = 6;
    public const uint TABLE_SCHED_SLICE = 1;
    public const uint TABLE_THREAD_STATE = 2;
    public const uint TABLE_CALLSTACK = 3;
    public const uint TABLE_MEASURE = 4;
    public const uint TABLE_PROCESS_MEASURE = 5;
    public const uint TABLE_FRAME_SLICE = 6;
    public const uint STYLE_RUNNING = 1;
    public const uint STYLE_RUNNABLE = 2;
    public const uint STYLE_BLOCKED = 3;
    public const uint STYLE_SLEEPING = 4;
    public const uint STYLE_COUNTER = 5;
    public const uint STYLE_ACCENT = 6;
    public const uint DOMINANT_NAME = 2;
    public const uint DOMINANT_THREAD_STATE = 3;
    public const uint DOMINANT_JANK = 4;
    public const uint QUALITY_PROBE_TRUNCATED = 1;
    public const uint QUALITY_INVALID_VALUE = 2;
    public const uint QUALITY_CLAMPED_VALUE = 3;
    public const uint QUALITY_DROPPED_VALUE = 4;
    public const uint QUALITY_REFERENTIAL_INTEGRITY = 5;
    public const uint QUALITY_UNAVAILABLE_VALUE = 6;
    public const uint QUALITY_UNCLASSIFIED = 7;
    public const uint PROGRESS_SOURCE_SNAPSHOT = 1;
    public const uint PROGRESS_PARSER_IDENTITY = 2;
    public const uint PROGRESS_PARSING = 3;
    public const uint PROGRESS_INDEXING = 4;
    public const uint PROGRESS_VALIDATING = 5;
    public const uint PROGRESS_PUBLISHING = 6;
    public const uint PROGRESS_OPENING_DATABASE = 7;
    public const uint PROGRESS_READY = 8;
    public const uint DOMINANT_IDENTITY = 1;
    public const uint QUALITY_STATUS_OK = 1;
    public const uint QUALITY_STATUS_WARNINGS = 2;
    public const uint CAP_CACHE_MAINTENANCE = 16;
    public const uint CACHE_INVENTORY = 1;
    public const uint CACHE_MAINTAIN = 2;
    public const uint CACHE_PURGE_UNUSED = 3;
    public const uint CAP_VIEW_STATE = 32;
    public const uint VIEW_STATE_READ = 1;
    public const uint VIEW_STATE_WRITE = 2;
    public const uint VIEW_STATE_REMOVE = 3;
    public const uint MAXIMUM_VIEW_STATE_BYTES = 4194304;
    public const uint MAXIMUM_RETAINED_VIEW_STATE_INPUT_BYTES = 16777216;
    public const uint CAP_VIEW_STATE_BACKUP = 128;
    public const uint VIEW_STATE_BACKUP = 5;
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_abi_identity")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_abi_identity(AbiIdentity* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_engine_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_engine_create(byte* input, ulong input_bytes, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_engine_create_fixture")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_engine_create_fixture(byte* input, ulong input_bytes, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_engine_drain")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_engine_drain(ulong engine);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_engine_drain_status")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_engine_drain_status(ulong engine, uint* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_engine_release")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_engine_release(ulong engine);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_session_open")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_session_open(ulong engine, byte* source, ulong source_bytes, uint format, uint timeout_ms, OpenTicket* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_session_poll")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_session_poll(ulong engine, ulong session, SessionStatus* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_session_close")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_session_close(ulong engine, ulong session);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_session_release")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_session_release(ulong engine, ulong session);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_cache_request_submit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_cache_request_submit(ulong engine, uint operation, uint timeout_ms, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_view_state_request_submit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_view_state_request_submit(ulong engine, ulong session, uint operation, byte* input, ulong input_bytes, uint timeout_ms, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_request_submit")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_request_submit(ulong engine, ulong session, byte* input, ulong input_bytes, uint timeout_ms, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_request_poll")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_request_poll(ulong engine, ulong request, PollStatus* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_request_cancel")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_request_cancel(ulong engine, ulong request);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_request_release")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_request_release(ulong engine, ulong request);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_result_acquire")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_result_acquire(ulong engine, ulong request, ResultView* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_result_view")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_result_view(ulong owner, ResultView* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_result_clone")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_result_clone(ulong owner, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_result_release")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_result_release(ulong owner);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_snapshot_acquire")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_snapshot_acquire(ulong engine, ulong request, SnapshotView* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_snapshot_view")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_snapshot_view(ulong owner, SnapshotView* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_fixture_panic")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_fixture_panic(ulong engine);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_engine_retained_result_bytes")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_engine_retained_result_bytes(ulong engine, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_engine_retained_view_state_input_bytes")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_engine_retained_view_state_input_bytes(ulong engine, ulong* output, ulong output_bytes);
    [LibraryImport("arktrace_ffi", EntryPoint = "arktrace_session_error_acquire")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint arktrace_session_error_acquire(ulong engine, ulong session, ResultView* output, ulong output_bytes);
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct AbiIdentity
{
    public uint struct_size;
    public uint abi_version;
    public ulong capabilities;
    public fixed byte contract_digest[32];
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct OpenTicket
{
    public uint struct_size;
    public uint reserved;
    public ulong session;
    public ulong request;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct PollStatus
{
    public uint struct_size;
    public uint state;
    public ulong session;
    public uint progress;
    public uint failure_present;
    public uint code;
    public uint stage;
    public uint retryable;
    public uint reserved;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct SessionStatus
{
    public uint struct_size;
    public uint state;
    public uint resources_closed;
    public uint failure_present;
    public uint code;
    public uint stage;
    public uint retryable;
    public uint reserved;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ResultView
{
    public uint struct_size;
    public uint kind;
    public ulong owner;
    public byte* data;
    public ulong length;
    public ulong retained_bytes;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct ViewportRecord
{
    public long start_ns;
    public long end_ns;
    public double ns_per_point;
    public double width_points;
    public double height_points;
    public double vertical_offset_points;
    public ulong generation;
    public ulong source_generation;
    public double backing_scale;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct TrackRecord
{
    public uint source_kind;
    public uint flags;
    public long source_value;
    public long filter_id;
    public long owner_value;
    public uint id_offset;
    public uint id_length;
    public double y;
    public double height;
    public uint depth_rows;
    public uint primitive_start;
    public uint primitive_count;
    public uint reserved;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct PrimitiveRecord
{
    public uint kind;
    public uint flags;
    public uint track_index;
    public uint event_table;
    public uint style;
    public uint reserved_header;
    public long depth;
    public long row_id;
    public long start_ns;
    public long end_ns;
    public double x;
    public double y;
    public double width;
    public double height;
    public long event_count;
    public long occupied_ns;
    public double utilization;
    public uint dominant_kind;
    public uint text_offset;
    public uint text_length;
    public uint reserved;
    public long dominant_value;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct QualityRecord
{
    public uint category;
    public uint flags;
    public uint scope_offset;
    public uint scope_length;
    public long count;
}
[StructLayout(LayoutKind.Sequential)]
public unsafe struct SnapshotView
{
    public uint struct_size;
    public uint format_version;
    public ulong owner;
    public ViewportRecord viewport;
    public TrackRecord* tracks;
    public ulong track_count;
    public PrimitiveRecord* primitives;
    public ulong primitive_count;
    public QualityRecord* quality;
    public ulong quality_count;
    public byte* strings;
    public ulong string_bytes;
    public ulong retained_bytes;
    public uint quality_status;
    public uint reserved;
}
