// Generated by scripts/generate_ffi_bindings.py; do not edit.
use arktrace_viewer::{PrimitiveRecord, QualityRecord, TrackRecord, ViewportRecord};
pub const ABI_VERSION: u32 = 1;
pub const CONTRACT_DIGEST_HEX: &str =
    "5c64c94cb0981e4e209ff6c2808964d8ee26062ca04cf0e2b810d945f491a9bc";
pub const CONTRACT_DIGEST: [u8; 32] = [
    92, 100, 201, 76, 176, 152, 30, 78, 32, 159, 246, 194, 128, 137, 100, 216, 238, 38, 6, 44, 160,
    76, 240, 226, 184, 16, 217, 69, 244, 145, 169, 188,
];
pub const STATUS_OK: u32 = 0;
pub const STATUS_BUSY: u32 = 1;
pub const STATUS_CAPACITY: u32 = 2;
pub const STATUS_INVALID_INPUT: u32 = 3;
pub const STATUS_INVALID_BUFFER: u32 = 4;
pub const STATUS_INVALID_HANDLE: u32 = 5;
pub const STATUS_ABI_MISMATCH: u32 = 6;
pub const STATUS_UNSUPPORTED_HOST: u32 = 7;
pub const STATUS_CLOSED: u32 = 8;
pub const STATUS_CANCELLED: u32 = 9;
pub const STATUS_INTERNAL: u32 = 10;
pub const STATUS_UNSUPPORTED_OPERATION: u32 = 11;
pub const STATUS_OUTPUT_LIMIT: u32 = 12;
pub const STATUS_POISONED: u32 = 13;
pub const CAP_MACOS_ENGINE: u32 = 1;
pub const CAP_COLD_JSON: u32 = 2;
pub const CAP_VIEWPORT_RECORDS: u32 = 4;
pub const CAP_DEVELOPMENT_FIXTURES: u32 = 8;
pub const RESULT_SUCCESS: u32 = 0;
pub const RESULT_FAILURE: u32 = 1;
pub const REQUEST_QUEUED: u32 = 1;
pub const REQUEST_RUNNING: u32 = 2;
pub const REQUEST_CANCELLING: u32 = 3;
pub const REQUEST_SUCCEEDED: u32 = 4;
pub const REQUEST_FAILED: u32 = 5;
pub const SESSION_OPENING: u32 = 1;
pub const SESSION_READY: u32 = 2;
pub const SESSION_CANCELLING: u32 = 3;
pub const SESSION_CLOSING: u32 = 4;
pub const SESSION_FAILED: u32 = 5;
pub const SESSION_CLOSED: u32 = 6;
pub const DRAIN_RUNNING: u32 = 1;
pub const DRAIN_DRAINING: u32 = 2;
pub const DRAIN_DRAINED: u32 = 3;
pub const PRIMITIVE_DETAIL: u32 = 1;
pub const PRIMITIVE_DENSITY: u32 = 2;
pub const FLAG_VISIBLE: u32 = 1;
pub const FLAG_FRAME: u32 = 2;
pub const FLAG_OPEN_ENDED: u32 = 4;
pub const FLAG_OCCUPANCY: u32 = 8;
pub const FLAG_UTILIZATION: u32 = 16;
pub const TRACK_COLLAPSED: u32 = 1;
pub const TRACK_NESTED: u32 = 2;
pub const TRACK_OWNER: u32 = 4;
pub const QUALITY_SCOPE: u32 = 1;
pub const QUALITY_COUNT: u32 = 2;
pub const MAXIMUM_ENGINES: u32 = 8;
pub const MAXIMUM_RESULT_OWNERS: u32 = 256;
pub const MAXIMUM_CONFIG_BYTES: u32 = 16384;
pub const MAXIMUM_REQUEST_BYTES: u32 = 1048576;
pub const MAXIMUM_PATH_BYTES: u32 = 4096;
pub const CODE_INVALID_ARGUMENT: u32 = 1;
pub const CODE_TRACE_FILE_NOT_FOUND: u32 = 2;
pub const CODE_TRACE_FILE_UNREADABLE: u32 = 3;
pub const CODE_TRACE_FORMAT_UNSUPPORTED: u32 = 4;
pub const CODE_TRACE_STREAMER_UNAVAILABLE: u32 = 5;
pub const CODE_TRACE_STREAMER_IDENTITY_MISMATCH: u32 = 6;
pub const CODE_TRACE_PARSE_FAILED: u32 = 7;
pub const CODE_TRACE_SCHEMA_UNSUPPORTED: u32 = 8;
pub const CODE_TRACE_DATABASE_INVALID: u32 = 9;
pub const CODE_TRACE_CACHE_CORRUPT: u32 = 10;
pub const CODE_QUERY_FAILED: u32 = 11;
pub const CODE_QUERY_TIMEOUT: u32 = 12;
pub const CODE_QUERY_LIMIT_EXCEEDED: u32 = 13;
pub const CODE_OUTPUT_LIMIT_EXCEEDED: u32 = 14;
pub const CODE_ANALYSIS_UNSUPPORTED: u32 = 15;
pub const CODE_CANCELLED: u32 = 16;
pub const CODE_INTERNAL_ERROR: u32 = 17;
pub const STAGE_REQUEST: u32 = 1;
pub const STAGE_PREPARING: u32 = 2;
pub const STAGE_HASHING: u32 = 3;
pub const STAGE_CACHE_LOOKUP: u32 = 4;
pub const STAGE_PARSING: u32 = 5;
pub const STAGE_VALIDATING: u32 = 6;
pub const STAGE_INDEXING: u32 = 7;
pub const STAGE_OPENING_DATABASE: u32 = 8;
pub const STAGE_QUERYING: u32 = 9;
pub const STAGE_ANALYZING: u32 = 10;
pub const STAGE_ENCODING: u32 = 11;
pub const SOURCE_CPU: u32 = 1;
pub const SOURCE_THREAD_STATE: u32 = 2;
pub const SOURCE_NAMED_SLICE: u32 = 3;
pub const SOURCE_CPU_COUNTER: u32 = 4;
pub const SOURCE_PROCESS_COUNTER: u32 = 5;
pub const SOURCE_FRAME: u32 = 6;
pub const TABLE_SCHED_SLICE: u32 = 1;
pub const TABLE_THREAD_STATE: u32 = 2;
pub const TABLE_CALLSTACK: u32 = 3;
pub const TABLE_MEASURE: u32 = 4;
pub const TABLE_PROCESS_MEASURE: u32 = 5;
pub const TABLE_FRAME_SLICE: u32 = 6;
pub const STYLE_RUNNING: u32 = 1;
pub const STYLE_RUNNABLE: u32 = 2;
pub const STYLE_BLOCKED: u32 = 3;
pub const STYLE_SLEEPING: u32 = 4;
pub const STYLE_COUNTER: u32 = 5;
pub const STYLE_ACCENT: u32 = 6;
pub const DOMINANT_NAME: u32 = 2;
pub const DOMINANT_THREAD_STATE: u32 = 3;
pub const DOMINANT_JANK: u32 = 4;
pub const QUALITY_PROBE_TRUNCATED: u32 = 1;
pub const QUALITY_INVALID_VALUE: u32 = 2;
pub const QUALITY_CLAMPED_VALUE: u32 = 3;
pub const QUALITY_DROPPED_VALUE: u32 = 4;
pub const QUALITY_REFERENTIAL_INTEGRITY: u32 = 5;
pub const QUALITY_UNAVAILABLE_VALUE: u32 = 6;
pub const QUALITY_UNCLASSIFIED: u32 = 7;
pub const PROGRESS_SOURCE_SNAPSHOT: u32 = 1;
pub const PROGRESS_PARSER_IDENTITY: u32 = 2;
pub const PROGRESS_PARSING: u32 = 3;
pub const PROGRESS_INDEXING: u32 = 4;
pub const PROGRESS_VALIDATING: u32 = 5;
pub const PROGRESS_PUBLISHING: u32 = 6;
pub const PROGRESS_OPENING_DATABASE: u32 = 7;
pub const PROGRESS_READY: u32 = 8;
pub const DOMINANT_IDENTITY: u32 = 1;
pub const QUALITY_STATUS_OK: u32 = 1;
pub const QUALITY_STATUS_WARNINGS: u32 = 2;
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct AbiIdentity {
    pub struct_size: u32,
    pub abi_version: u32,
    pub capabilities: u64,
    pub contract_digest: [u8; 32],
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<AbiIdentity>() == 48);
    assert!(std::mem::align_of::<AbiIdentity>() == 8);
    assert!(std::mem::offset_of!(AbiIdentity, struct_size) == 0);
    assert!(std::mem::offset_of!(AbiIdentity, abi_version) == 4);
    assert!(std::mem::offset_of!(AbiIdentity, capabilities) == 8);
    assert!(std::mem::offset_of!(AbiIdentity, contract_digest) == 16);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct OpenTicket {
    pub struct_size: u32,
    pub reserved: u32,
    pub session: u64,
    pub request: u64,
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<OpenTicket>() == 24);
    assert!(std::mem::align_of::<OpenTicket>() == 8);
    assert!(std::mem::offset_of!(OpenTicket, struct_size) == 0);
    assert!(std::mem::offset_of!(OpenTicket, reserved) == 4);
    assert!(std::mem::offset_of!(OpenTicket, session) == 8);
    assert!(std::mem::offset_of!(OpenTicket, request) == 16);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct PollStatus {
    pub struct_size: u32,
    pub state: u32,
    pub session: u64,
    pub progress: u32,
    pub failure_present: u32,
    pub code: u32,
    pub stage: u32,
    pub retryable: u32,
    pub reserved: u32,
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<PollStatus>() == 40);
    assert!(std::mem::align_of::<PollStatus>() == 8);
    assert!(std::mem::offset_of!(PollStatus, struct_size) == 0);
    assert!(std::mem::offset_of!(PollStatus, state) == 4);
    assert!(std::mem::offset_of!(PollStatus, session) == 8);
    assert!(std::mem::offset_of!(PollStatus, progress) == 16);
    assert!(std::mem::offset_of!(PollStatus, failure_present) == 20);
    assert!(std::mem::offset_of!(PollStatus, code) == 24);
    assert!(std::mem::offset_of!(PollStatus, stage) == 28);
    assert!(std::mem::offset_of!(PollStatus, retryable) == 32);
    assert!(std::mem::offset_of!(PollStatus, reserved) == 36);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct SessionStatus {
    pub struct_size: u32,
    pub state: u32,
    pub resources_closed: u32,
    pub failure_present: u32,
    pub code: u32,
    pub stage: u32,
    pub retryable: u32,
    pub reserved: u32,
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<SessionStatus>() == 32);
    assert!(std::mem::align_of::<SessionStatus>() == 4);
    assert!(std::mem::offset_of!(SessionStatus, struct_size) == 0);
    assert!(std::mem::offset_of!(SessionStatus, state) == 4);
    assert!(std::mem::offset_of!(SessionStatus, resources_closed) == 8);
    assert!(std::mem::offset_of!(SessionStatus, failure_present) == 12);
    assert!(std::mem::offset_of!(SessionStatus, code) == 16);
    assert!(std::mem::offset_of!(SessionStatus, stage) == 20);
    assert!(std::mem::offset_of!(SessionStatus, retryable) == 24);
    assert!(std::mem::offset_of!(SessionStatus, reserved) == 28);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ResultView {
    pub struct_size: u32,
    pub kind: u32,
    pub owner: u64,
    pub data: *const u8,
    pub length: u64,
    pub retained_bytes: u64,
}
impl Default for ResultView {
    fn default() -> Self {
        Self {
            struct_size: Default::default(),
            kind: Default::default(),
            owner: Default::default(),
            data: std::ptr::null(),
            length: Default::default(),
            retained_bytes: Default::default(),
        }
    }
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<ResultView>() == 40);
    assert!(std::mem::align_of::<ResultView>() == 8);
    assert!(std::mem::offset_of!(ResultView, struct_size) == 0);
    assert!(std::mem::offset_of!(ResultView, kind) == 4);
    assert!(std::mem::offset_of!(ResultView, owner) == 8);
    assert!(std::mem::offset_of!(ResultView, data) == 16);
    assert!(std::mem::offset_of!(ResultView, length) == 24);
    assert!(std::mem::offset_of!(ResultView, retained_bytes) == 32);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SnapshotView {
    pub struct_size: u32,
    pub format_version: u32,
    pub owner: u64,
    pub viewport: ViewportRecord,
    pub tracks: *const TrackRecord,
    pub track_count: u64,
    pub primitives: *const PrimitiveRecord,
    pub primitive_count: u64,
    pub quality: *const QualityRecord,
    pub quality_count: u64,
    pub strings: *const u8,
    pub string_bytes: u64,
    pub retained_bytes: u64,
    pub quality_status: u32,
    pub reserved: u32,
}
impl Default for SnapshotView {
    fn default() -> Self {
        Self {
            struct_size: Default::default(),
            format_version: Default::default(),
            owner: Default::default(),
            viewport: Default::default(),
            tracks: std::ptr::null(),
            track_count: Default::default(),
            primitives: std::ptr::null(),
            primitive_count: Default::default(),
            quality: std::ptr::null(),
            quality_count: Default::default(),
            strings: std::ptr::null(),
            string_bytes: Default::default(),
            retained_bytes: Default::default(),
            quality_status: Default::default(),
            reserved: Default::default(),
        }
    }
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<SnapshotView>() == 168);
    assert!(std::mem::align_of::<SnapshotView>() == 8);
    assert!(std::mem::offset_of!(SnapshotView, struct_size) == 0);
    assert!(std::mem::offset_of!(SnapshotView, format_version) == 4);
    assert!(std::mem::offset_of!(SnapshotView, owner) == 8);
    assert!(std::mem::offset_of!(SnapshotView, viewport) == 16);
    assert!(std::mem::offset_of!(SnapshotView, tracks) == 88);
    assert!(std::mem::offset_of!(SnapshotView, track_count) == 96);
    assert!(std::mem::offset_of!(SnapshotView, primitives) == 104);
    assert!(std::mem::offset_of!(SnapshotView, primitive_count) == 112);
    assert!(std::mem::offset_of!(SnapshotView, quality) == 120);
    assert!(std::mem::offset_of!(SnapshotView, quality_count) == 128);
    assert!(std::mem::offset_of!(SnapshotView, strings) == 136);
    assert!(std::mem::offset_of!(SnapshotView, string_bytes) == 144);
    assert!(std::mem::offset_of!(SnapshotView, retained_bytes) == 152);
    assert!(std::mem::offset_of!(SnapshotView, quality_status) == 160);
    assert!(std::mem::offset_of!(SnapshotView, reserved) == 164);
};
