/* Generated by scripts/generate_ffi_bindings.py; do not edit. */
#ifndef ARKTRACE_FFI_H
#define ARKTRACE_FFI_H
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
extern "C" {
#define ARKTRACE_LAYOUT_ASSERT static_assert
#else
#define ARKTRACE_LAYOUT_ASSERT _Static_assert
#endif
ARKTRACE_LAYOUT_ASSERT(sizeof(void *) == 8, "ArkTrace ABI requires a 64-bit host");
#define ARKTRACE_ABI_VERSION 2u
#define ARKTRACE_CONTRACT_DIGEST "bf21cbfb22e4afc34b8169f9961c27119ffa789154e441a838de4240ad3b8617"
/* Input/output storage must be valid, correctly aligned, live and non-overlapping. Inputs are copied before return; output records use exact byte sizes. Rust owners retain immutable data through release/close/drain; view memory remains live until its owner is released. No arbitrary dangling-pointer safety is claimed. */
/* Exports catch Rust unwind; an unexpected export panic poisons and drains its Engine. Worker failures preserve actual session/cleanup errors. OOM/native faults may terminate the process. */
#define ARKTRACE_SNAPSHOT_FORMAT_VERSION 2u
#define ARKTRACE_STATUS_OK 0u
#define ARKTRACE_STATUS_BUSY 1u
#define ARKTRACE_STATUS_CAPACITY 2u
#define ARKTRACE_STATUS_INVALID_INPUT 3u
#define ARKTRACE_STATUS_INVALID_BUFFER 4u
#define ARKTRACE_STATUS_INVALID_HANDLE 5u
#define ARKTRACE_STATUS_ABI_MISMATCH 6u
#define ARKTRACE_STATUS_UNSUPPORTED_HOST 7u
#define ARKTRACE_STATUS_CLOSED 8u
#define ARKTRACE_STATUS_CANCELLED 9u
#define ARKTRACE_STATUS_INTERNAL 10u
#define ARKTRACE_STATUS_UNSUPPORTED_OPERATION 11u
#define ARKTRACE_STATUS_OUTPUT_LIMIT 12u
#define ARKTRACE_STATUS_POISONED 13u
#define ARKTRACE_CAP_MACOS_ENGINE 1u
#define ARKTRACE_CAP_COLD_JSON 2u
#define ARKTRACE_CAP_VIEWPORT_RECORDS 4u
#define ARKTRACE_CAP_DEVELOPMENT_FIXTURES 8u
#define ARKTRACE_RESULT_SUCCESS 0u
#define ARKTRACE_RESULT_FAILURE 1u
#define ARKTRACE_REQUEST_QUEUED 1u
#define ARKTRACE_REQUEST_RUNNING 2u
#define ARKTRACE_REQUEST_CANCELLING 3u
#define ARKTRACE_REQUEST_SUCCEEDED 4u
#define ARKTRACE_REQUEST_FAILED 5u
#define ARKTRACE_SESSION_OPENING 1u
#define ARKTRACE_SESSION_READY 2u
#define ARKTRACE_SESSION_CANCELLING 3u
#define ARKTRACE_SESSION_CLOSING 4u
#define ARKTRACE_SESSION_FAILED 5u
#define ARKTRACE_SESSION_CLOSED 6u
#define ARKTRACE_DRAIN_RUNNING 1u
#define ARKTRACE_DRAIN_DRAINING 2u
#define ARKTRACE_DRAIN_DRAINED 3u
#define ARKTRACE_PRIMITIVE_DETAIL 1u
#define ARKTRACE_PRIMITIVE_DENSITY 2u
#define ARKTRACE_FLAG_VISIBLE 1u
#define ARKTRACE_FLAG_FRAME 2u
#define ARKTRACE_FLAG_OPEN_ENDED 4u
#define ARKTRACE_FLAG_OCCUPANCY 8u
#define ARKTRACE_FLAG_UTILIZATION 16u
#define ARKTRACE_TRACK_COLLAPSED 1u
#define ARKTRACE_TRACK_NESTED 2u
#define ARKTRACE_TRACK_OWNER 4u
#define ARKTRACE_QUALITY_SCOPE 1u
#define ARKTRACE_QUALITY_COUNT 2u
#define ARKTRACE_MAXIMUM_ENGINES 8u
#define ARKTRACE_MAXIMUM_RESULT_OWNERS 256u
#define ARKTRACE_MAXIMUM_CONFIG_BYTES 16384u
#define ARKTRACE_MAXIMUM_REQUEST_BYTES 1048576u
#define ARKTRACE_MAXIMUM_PATH_BYTES 4096u
#define ARKTRACE_CODE_INVALID_ARGUMENT 1u
#define ARKTRACE_CODE_TRACE_FILE_NOT_FOUND 2u
#define ARKTRACE_CODE_TRACE_FILE_UNREADABLE 3u
#define ARKTRACE_CODE_TRACE_FORMAT_UNSUPPORTED 4u
#define ARKTRACE_CODE_TRACE_STREAMER_UNAVAILABLE 5u
#define ARKTRACE_CODE_TRACE_STREAMER_IDENTITY_MISMATCH 6u
#define ARKTRACE_CODE_TRACE_PARSE_FAILED 7u
#define ARKTRACE_CODE_TRACE_SCHEMA_UNSUPPORTED 8u
#define ARKTRACE_CODE_TRACE_DATABASE_INVALID 9u
#define ARKTRACE_CODE_TRACE_CACHE_CORRUPT 10u
#define ARKTRACE_CODE_QUERY_FAILED 11u
#define ARKTRACE_CODE_QUERY_TIMEOUT 12u
#define ARKTRACE_CODE_QUERY_LIMIT_EXCEEDED 13u
#define ARKTRACE_CODE_OUTPUT_LIMIT_EXCEEDED 14u
#define ARKTRACE_CODE_ANALYSIS_UNSUPPORTED 15u
#define ARKTRACE_CODE_CANCELLED 16u
#define ARKTRACE_CODE_INTERNAL_ERROR 17u
#define ARKTRACE_STAGE_REQUEST 1u
#define ARKTRACE_STAGE_PREPARING 2u
#define ARKTRACE_STAGE_HASHING 3u
#define ARKTRACE_STAGE_CACHE_LOOKUP 4u
#define ARKTRACE_STAGE_PARSING 5u
#define ARKTRACE_STAGE_VALIDATING 6u
#define ARKTRACE_STAGE_INDEXING 7u
#define ARKTRACE_STAGE_OPENING_DATABASE 8u
#define ARKTRACE_STAGE_QUERYING 9u
#define ARKTRACE_STAGE_ANALYZING 10u
#define ARKTRACE_STAGE_ENCODING 11u
#define ARKTRACE_SOURCE_CPU 1u
#define ARKTRACE_SOURCE_THREAD_STATE 2u
#define ARKTRACE_SOURCE_NAMED_SLICE 3u
#define ARKTRACE_SOURCE_CPU_COUNTER 4u
#define ARKTRACE_SOURCE_PROCESS_COUNTER 5u
#define ARKTRACE_SOURCE_FRAME 6u
#define ARKTRACE_TABLE_SCHED_SLICE 1u
#define ARKTRACE_TABLE_THREAD_STATE 2u
#define ARKTRACE_TABLE_CALLSTACK 3u
#define ARKTRACE_TABLE_MEASURE 4u
#define ARKTRACE_TABLE_PROCESS_MEASURE 5u
#define ARKTRACE_TABLE_FRAME_SLICE 6u
#define ARKTRACE_STYLE_RUNNING 1u
#define ARKTRACE_STYLE_RUNNABLE 2u
#define ARKTRACE_STYLE_BLOCKED 3u
#define ARKTRACE_STYLE_SLEEPING 4u
#define ARKTRACE_STYLE_COUNTER 5u
#define ARKTRACE_STYLE_ACCENT 6u
#define ARKTRACE_DOMINANT_NAME 2u
#define ARKTRACE_DOMINANT_THREAD_STATE 3u
#define ARKTRACE_DOMINANT_JANK 4u
#define ARKTRACE_QUALITY_PROBE_TRUNCATED 1u
#define ARKTRACE_QUALITY_INVALID_VALUE 2u
#define ARKTRACE_QUALITY_CLAMPED_VALUE 3u
#define ARKTRACE_QUALITY_DROPPED_VALUE 4u
#define ARKTRACE_QUALITY_REFERENTIAL_INTEGRITY 5u
#define ARKTRACE_QUALITY_UNAVAILABLE_VALUE 6u
#define ARKTRACE_QUALITY_UNCLASSIFIED 7u
#define ARKTRACE_PROGRESS_SOURCE_SNAPSHOT 1u
#define ARKTRACE_PROGRESS_PARSER_IDENTITY 2u
#define ARKTRACE_PROGRESS_PARSING 3u
#define ARKTRACE_PROGRESS_INDEXING 4u
#define ARKTRACE_PROGRESS_VALIDATING 5u
#define ARKTRACE_PROGRESS_PUBLISHING 6u
#define ARKTRACE_PROGRESS_OPENING_DATABASE 7u
#define ARKTRACE_PROGRESS_READY 8u
#define ARKTRACE_DOMINANT_IDENTITY 1u
#define ARKTRACE_QUALITY_STATUS_OK 1u
#define ARKTRACE_QUALITY_STATUS_WARNINGS 2u
#define ARKTRACE_CAP_CACHE_MAINTENANCE 16u
#define ARKTRACE_CACHE_INVENTORY 1u
#define ARKTRACE_CACHE_MAINTAIN 2u
#define ARKTRACE_CACHE_PURGE_UNUSED 3u
#define ARKTRACE_CAP_VIEW_STATE 32u
#define ARKTRACE_VIEW_STATE_READ 1u
#define ARKTRACE_VIEW_STATE_WRITE 2u
#define ARKTRACE_VIEW_STATE_REMOVE 3u
#define ARKTRACE_MAXIMUM_VIEW_STATE_BYTES 4194304u
#define ARKTRACE_MAXIMUM_RETAINED_VIEW_STATE_INPUT_BYTES 16777216u
#define ARKTRACE_CAP_VIEW_STATE_BACKUP 128u
#define ARKTRACE_VIEW_STATE_BACKUP 5u
#define ARKTRACE_FLAG_RENDER_FACTS 32u
#define ARKTRACE_FLAG_LABEL 64u
#define ARKTRACE_FLAG_CATEGORY 128u
#define ARKTRACE_FLAG_NAME 256u
#define ARKTRACE_FLAG_PROCESS_NAME 512u
#define ARKTRACE_FLAG_THREAD_NAME 1024u
#define ARKTRACE_FLAG_INSPECTOR_CATEGORY 2048u
#define ARKTRACE_FLAG_STATE 4096u
#define ARKTRACE_FLAG_UNIT 8192u
#define ARKTRACE_FLAG_SEMANTIC_DURATION 16384u
#define ARKTRACE_FLAG_PROCESS_KEY 32768u
#define ARKTRACE_FLAG_THREAD_KEY 65536u
#define ARKTRACE_FLAG_PID 131072u
#define ARKTRACE_FLAG_TID 262144u
#define ARKTRACE_FLAG_CPU 524288u
#define ARKTRACE_FLAG_VALUE 1048576u
#define ARKTRACE_FLAG_PRIORITY 2097152u
#define ARKTRACE_FLAG_COLOR 4194304u
typedef struct ArkTraceAbiIdentity {
    uint32_t struct_size;
    uint32_t abi_version;
    uint64_t capabilities;
    uint8_t contract_digest[32];
} ArkTraceAbiIdentity;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceAbiIdentity) == 48, "AbiIdentity size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceAbiIdentity, struct_size) == 0, "AbiIdentity.struct_size offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceAbiIdentity, abi_version) == 4, "AbiIdentity.abi_version offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceAbiIdentity, capabilities) == 8, "AbiIdentity.capabilities offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceAbiIdentity, contract_digest) == 16, "AbiIdentity.contract_digest offset");
typedef struct ArkTraceOpenTicket {
    uint32_t struct_size;
    uint32_t reserved;
    uint64_t session;
    uint64_t request;
} ArkTraceOpenTicket;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceOpenTicket) == 24, "OpenTicket size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceOpenTicket, struct_size) == 0, "OpenTicket.struct_size offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceOpenTicket, reserved) == 4, "OpenTicket.reserved offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceOpenTicket, session) == 8, "OpenTicket.session offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceOpenTicket, request) == 16, "OpenTicket.request offset");
typedef struct ArkTracePollStatus {
    uint32_t struct_size;
    uint32_t state;
    uint64_t session;
    uint32_t progress;
    uint32_t failure_present;
    uint32_t code;
    uint32_t stage;
    uint32_t retryable;
    uint32_t reserved;
} ArkTracePollStatus;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTracePollStatus) == 40, "PollStatus size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, struct_size) == 0, "PollStatus.struct_size offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, state) == 4, "PollStatus.state offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, session) == 8, "PollStatus.session offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, progress) == 16, "PollStatus.progress offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, failure_present) == 20, "PollStatus.failure_present offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, code) == 24, "PollStatus.code offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, stage) == 28, "PollStatus.stage offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, retryable) == 32, "PollStatus.retryable offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePollStatus, reserved) == 36, "PollStatus.reserved offset");
typedef struct ArkTraceSessionStatus {
    uint32_t struct_size;
    uint32_t state;
    uint32_t resources_closed;
    uint32_t failure_present;
    uint32_t code;
    uint32_t stage;
    uint32_t retryable;
    uint32_t reserved;
} ArkTraceSessionStatus;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceSessionStatus) == 32, "SessionStatus size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, struct_size) == 0, "SessionStatus.struct_size offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, state) == 4, "SessionStatus.state offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, resources_closed) == 8, "SessionStatus.resources_closed offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, failure_present) == 12, "SessionStatus.failure_present offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, code) == 16, "SessionStatus.code offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, stage) == 20, "SessionStatus.stage offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, retryable) == 24, "SessionStatus.retryable offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSessionStatus, reserved) == 28, "SessionStatus.reserved offset");
typedef struct ArkTraceResultView {
    uint32_t struct_size;
    uint32_t kind;
    uint64_t owner;
    const uint8_t * data;
    uint64_t length;
    uint64_t retained_bytes;
} ArkTraceResultView;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceResultView) == 40, "ResultView size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceResultView, struct_size) == 0, "ResultView.struct_size offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceResultView, kind) == 4, "ResultView.kind offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceResultView, owner) == 8, "ResultView.owner offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceResultView, data) == 16, "ResultView.data offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceResultView, length) == 24, "ResultView.length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceResultView, retained_bytes) == 32, "ResultView.retained_bytes offset");
typedef struct ArkTraceViewportRecord {
    int64_t start_ns;
    int64_t end_ns;
    double ns_per_point;
    double width_points;
    double height_points;
    double vertical_offset_points;
    uint64_t generation;
    uint64_t source_generation;
    double backing_scale;
} ArkTraceViewportRecord;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceViewportRecord) == 72, "ViewportRecord size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, start_ns) == 0, "ViewportRecord.start_ns offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, end_ns) == 8, "ViewportRecord.end_ns offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, ns_per_point) == 16, "ViewportRecord.ns_per_point offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, width_points) == 24, "ViewportRecord.width_points offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, height_points) == 32, "ViewportRecord.height_points offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, vertical_offset_points) == 40, "ViewportRecord.vertical_offset_points offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, generation) == 48, "ViewportRecord.generation offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, source_generation) == 56, "ViewportRecord.source_generation offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceViewportRecord, backing_scale) == 64, "ViewportRecord.backing_scale offset");
typedef struct ArkTraceTrackRecord {
    uint32_t source_kind;
    uint32_t flags;
    int64_t source_value;
    int64_t filter_id;
    int64_t owner_value;
    uint32_t id_offset;
    uint32_t id_length;
    double y;
    double height;
    uint32_t depth_rows;
    uint32_t primitive_start;
    uint32_t primitive_count;
    uint32_t reserved;
} ArkTraceTrackRecord;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceTrackRecord) == 72, "TrackRecord size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, source_kind) == 0, "TrackRecord.source_kind offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, flags) == 4, "TrackRecord.flags offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, source_value) == 8, "TrackRecord.source_value offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, filter_id) == 16, "TrackRecord.filter_id offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, owner_value) == 24, "TrackRecord.owner_value offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, id_offset) == 32, "TrackRecord.id_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, id_length) == 36, "TrackRecord.id_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, y) == 40, "TrackRecord.y offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, height) == 48, "TrackRecord.height offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, depth_rows) == 56, "TrackRecord.depth_rows offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, primitive_start) == 60, "TrackRecord.primitive_start offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, primitive_count) == 64, "TrackRecord.primitive_count offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceTrackRecord, reserved) == 68, "TrackRecord.reserved offset");
typedef struct ArkTracePrimitiveRecord {
    uint32_t kind;
    uint32_t flags;
    uint32_t track_index;
    uint32_t event_table;
    uint32_t style;
    uint32_t reserved_header;
    int64_t depth;
    int64_t row_id;
    int64_t start_ns;
    int64_t end_ns;
    double x;
    double y;
    double width;
    double height;
    int64_t event_count;
    int64_t occupied_ns;
    double utilization;
    uint32_t dominant_kind;
    uint32_t text_offset;
    uint32_t text_length;
    uint32_t reserved;
    int64_t dominant_value;
    uint32_t event_kind;
    uint32_t color_rgb;
    int64_t jank_tag;
    int64_t semantic_duration_ns;
    int64_t process_key;
    int64_t thread_key;
    int64_t pid;
    int64_t tid;
    int64_t cpu;
    int64_t value;
    int64_t priority;
    uint32_t label_offset;
    uint32_t label_length;
    uint32_t category_offset;
    uint32_t category_length;
    uint32_t name_offset;
    uint32_t name_length;
    uint32_t process_name_offset;
    uint32_t process_name_length;
    uint32_t thread_name_offset;
    uint32_t thread_name_length;
    uint32_t inspector_category_offset;
    uint32_t inspector_category_length;
    uint32_t state_offset;
    uint32_t state_length;
    uint32_t unit_offset;
    uint32_t unit_length;
} ArkTracePrimitiveRecord;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTracePrimitiveRecord) == 280, "PrimitiveRecord size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, kind) == 0, "PrimitiveRecord.kind offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, flags) == 4, "PrimitiveRecord.flags offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, track_index) == 8, "PrimitiveRecord.track_index offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, event_table) == 12, "PrimitiveRecord.event_table offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, style) == 16, "PrimitiveRecord.style offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, reserved_header) == 20, "PrimitiveRecord.reserved_header offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, depth) == 24, "PrimitiveRecord.depth offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, row_id) == 32, "PrimitiveRecord.row_id offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, start_ns) == 40, "PrimitiveRecord.start_ns offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, end_ns) == 48, "PrimitiveRecord.end_ns offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, x) == 56, "PrimitiveRecord.x offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, y) == 64, "PrimitiveRecord.y offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, width) == 72, "PrimitiveRecord.width offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, height) == 80, "PrimitiveRecord.height offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, event_count) == 88, "PrimitiveRecord.event_count offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, occupied_ns) == 96, "PrimitiveRecord.occupied_ns offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, utilization) == 104, "PrimitiveRecord.utilization offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, dominant_kind) == 112, "PrimitiveRecord.dominant_kind offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, text_offset) == 116, "PrimitiveRecord.text_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, text_length) == 120, "PrimitiveRecord.text_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, reserved) == 124, "PrimitiveRecord.reserved offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, dominant_value) == 128, "PrimitiveRecord.dominant_value offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, event_kind) == 136, "PrimitiveRecord.event_kind offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, color_rgb) == 140, "PrimitiveRecord.color_rgb offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, jank_tag) == 144, "PrimitiveRecord.jank_tag offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, semantic_duration_ns) == 152, "PrimitiveRecord.semantic_duration_ns offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, process_key) == 160, "PrimitiveRecord.process_key offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, thread_key) == 168, "PrimitiveRecord.thread_key offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, pid) == 176, "PrimitiveRecord.pid offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, tid) == 184, "PrimitiveRecord.tid offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, cpu) == 192, "PrimitiveRecord.cpu offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, value) == 200, "PrimitiveRecord.value offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, priority) == 208, "PrimitiveRecord.priority offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, label_offset) == 216, "PrimitiveRecord.label_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, label_length) == 220, "PrimitiveRecord.label_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, category_offset) == 224, "PrimitiveRecord.category_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, category_length) == 228, "PrimitiveRecord.category_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, name_offset) == 232, "PrimitiveRecord.name_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, name_length) == 236, "PrimitiveRecord.name_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, process_name_offset) == 240, "PrimitiveRecord.process_name_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, process_name_length) == 244, "PrimitiveRecord.process_name_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, thread_name_offset) == 248, "PrimitiveRecord.thread_name_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, thread_name_length) == 252, "PrimitiveRecord.thread_name_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, inspector_category_offset) == 256, "PrimitiveRecord.inspector_category_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, inspector_category_length) == 260, "PrimitiveRecord.inspector_category_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, state_offset) == 264, "PrimitiveRecord.state_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, state_length) == 268, "PrimitiveRecord.state_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, unit_offset) == 272, "PrimitiveRecord.unit_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTracePrimitiveRecord, unit_length) == 276, "PrimitiveRecord.unit_length offset");
typedef struct ArkTraceQualityRecord {
    uint32_t category;
    uint32_t flags;
    uint32_t scope_offset;
    uint32_t scope_length;
    int64_t count;
} ArkTraceQualityRecord;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceQualityRecord) == 24, "QualityRecord size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceQualityRecord, category) == 0, "QualityRecord.category offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceQualityRecord, flags) == 4, "QualityRecord.flags offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceQualityRecord, scope_offset) == 8, "QualityRecord.scope_offset offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceQualityRecord, scope_length) == 12, "QualityRecord.scope_length offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceQualityRecord, count) == 16, "QualityRecord.count offset");
typedef struct ArkTraceSnapshotView {
    uint32_t struct_size;
    uint32_t format_version;
    uint64_t owner;
    ArkTraceViewportRecord viewport;
    const ArkTraceTrackRecord * tracks;
    uint64_t track_count;
    const ArkTracePrimitiveRecord * primitives;
    uint64_t primitive_count;
    const ArkTraceQualityRecord * quality;
    uint64_t quality_count;
    const uint8_t * strings;
    uint64_t string_bytes;
    uint64_t retained_bytes;
    uint32_t quality_status;
    uint32_t reserved;
} ArkTraceSnapshotView;
ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTraceSnapshotView) == 168, "SnapshotView size");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, struct_size) == 0, "SnapshotView.struct_size offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, format_version) == 4, "SnapshotView.format_version offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, owner) == 8, "SnapshotView.owner offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, viewport) == 16, "SnapshotView.viewport offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, tracks) == 88, "SnapshotView.tracks offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, track_count) == 96, "SnapshotView.track_count offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, primitives) == 104, "SnapshotView.primitives offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, primitive_count) == 112, "SnapshotView.primitive_count offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, quality) == 120, "SnapshotView.quality offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, quality_count) == 128, "SnapshotView.quality_count offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, strings) == 136, "SnapshotView.strings offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, string_bytes) == 144, "SnapshotView.string_bytes offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, retained_bytes) == 152, "SnapshotView.retained_bytes offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, quality_status) == 160, "SnapshotView.quality_status offset");
ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTraceSnapshotView, reserved) == 164, "SnapshotView.reserved offset");
uint32_t arktrace_abi_identity(ArkTraceAbiIdentity * output, uint64_t output_bytes);
uint32_t arktrace_engine_create(const uint8_t * input, uint64_t input_bytes, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_engine_create_fixture(const uint8_t * input, uint64_t input_bytes, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_engine_drain(uint64_t engine);
uint32_t arktrace_engine_drain_status(uint64_t engine, uint32_t * output, uint64_t output_bytes);
uint32_t arktrace_engine_release(uint64_t engine);
uint32_t arktrace_session_open(uint64_t engine, const uint8_t * source, uint64_t source_bytes, uint32_t format, uint32_t timeout_ms, ArkTraceOpenTicket * output, uint64_t output_bytes);
uint32_t arktrace_session_poll(uint64_t engine, uint64_t session, ArkTraceSessionStatus * output, uint64_t output_bytes);
uint32_t arktrace_session_close(uint64_t engine, uint64_t session);
uint32_t arktrace_session_release(uint64_t engine, uint64_t session);
uint32_t arktrace_cache_request_submit(uint64_t engine, uint32_t operation, uint32_t timeout_ms, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_view_state_request_submit(uint64_t engine, uint64_t session, uint32_t operation, const uint8_t * input, uint64_t input_bytes, uint32_t timeout_ms, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_request_submit(uint64_t engine, uint64_t session, const uint8_t * input, uint64_t input_bytes, uint32_t timeout_ms, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_request_poll(uint64_t engine, uint64_t request, ArkTracePollStatus * output, uint64_t output_bytes);
uint32_t arktrace_request_cancel(uint64_t engine, uint64_t request);
uint32_t arktrace_request_release(uint64_t engine, uint64_t request);
uint32_t arktrace_result_acquire(uint64_t engine, uint64_t request, ArkTraceResultView * output, uint64_t output_bytes);
uint32_t arktrace_result_view(uint64_t owner, ArkTraceResultView * output, uint64_t output_bytes);
uint32_t arktrace_result_clone(uint64_t owner, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_result_release(uint64_t owner);
uint32_t arktrace_snapshot_acquire(uint64_t engine, uint64_t request, ArkTraceSnapshotView * output, uint64_t output_bytes);
uint32_t arktrace_snapshot_view(uint64_t owner, ArkTraceSnapshotView * output, uint64_t output_bytes);
uint32_t arktrace_fixture_panic(uint64_t engine);
uint32_t arktrace_engine_retained_result_bytes(uint64_t engine, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_engine_retained_view_state_input_bytes(uint64_t engine, uint64_t * output, uint64_t output_bytes);
uint32_t arktrace_session_error_acquire(uint64_t engine, uint64_t session, ArkTraceResultView * output, uint64_t output_bytes);
#undef ARKTRACE_LAYOUT_ASSERT
#ifdef __cplusplus
}
#endif
#endif
