#!/usr/bin/env python3
"""Generate the C, Rust and C# ABI records from one reviewed contract."""
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'contracts/ffi-v1.json'
WIRE = {'ViewportRecord', 'TrackRecord', 'PrimitiveRecord', 'QualityRecord'}
SCALARS = {'u8': 'uint8_t', 'u32': 'uint32_t', 'u64': 'uint64_t', 'i64': 'int64_t', 'f64': 'double'}
CS = {'u8': 'byte', 'u32': 'uint', 'u64': 'ulong', 'i64': 'long', 'f64': 'double'}


def c_type(t):
    if t.endswith('*'):
        return ('const ' if t.startswith('const ') else '') + c_type(t.removeprefix('const ')[:-1]) + ' *'
    return SCALARS.get(t, 'ArkTrace' + t)


def rust_type(t):
    if t.endswith('*'):
        return ('*const ' if t.startswith('const ') else '*mut ') + rust_type(t.removeprefix('const ')[:-1])
    if '[' in t:
        base, count = t[:-1].split('[')
        return f'[{base}; {count}]'
    return t


def cs_type(t):
    if t.endswith('*'):
        return cs_type(t.removeprefix('const ')[:-1]) + '*'
    return CS.get(t, t)


def main():
    contract = json.loads(SOURCE.read_text())
    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    header = ['/* Generated by scripts/generate_ffi_bindings.py; do not edit. */', '#ifndef ARKTRACE_FFI_H', '#define ARKTRACE_FFI_H', '#include <stdint.h>', '#include <stddef.h>', '#ifdef __cplusplus', 'extern "C" {', '#define ARKTRACE_LAYOUT_ASSERT static_assert', '#else', '#define ARKTRACE_LAYOUT_ASSERT _Static_assert', '#endif', 'ARKTRACE_LAYOUT_ASSERT(sizeof(void *) == 8, "ArkTrace ABI requires a 64-bit host");', f'#define ARKTRACE_ABI_VERSION {contract["abiVersion"]}u', f'#define ARKTRACE_CONTRACT_DIGEST "{digest}"', '/* ' + contract['ownership'] + ' */', '/* ' + contract['panic'] + ' */']
    rust = ['// Generated by scripts/generate_ffi_bindings.py; do not edit.', 'use arktrace_viewer::{ViewportRecord, TrackRecord, PrimitiveRecord, QualityRecord};', f'pub const ABI_VERSION: u32 = {contract["abiVersion"]};', f'pub const CONTRACT_DIGEST_HEX: &str = "{digest}";', f'pub const CONTRACT_DIGEST: [u8; 32] = {list(bytes.fromhex(digest))!r};']
    wire = ['// Generated by scripts/generate_ffi_bindings.py; do not edit.']
    cs = ['// Generated by scripts/generate_ffi_bindings.py; do not edit.', 'using System.Runtime.CompilerServices;', 'using System.Runtime.InteropServices;', 'namespace ArkTrace.Native;', 'public static unsafe partial class NativeMethods', '{', f'    public const uint ABI_VERSION = {contract["abiVersion"]};', f'    public const string CONTRACT_DIGEST = "{digest}";']
    for k, v in contract['constants'].items():
        header.append(f'#define ARKTRACE_{k} {v}u')
        rust.append(f'pub const {k}: u32 = {v};')
        cs.append(f'    public const uint {k} = {v};')
        if k.startswith(('SOURCE_', 'TABLE_', 'STYLE_', 'DOMINANT_', 'QUALITY_', 'FLAG_', 'TRACK_', 'PRIMITIVE_')):
            wire.append(f'pub const WIRE_{k}: u32 = {v};')
    for fn in contract['functions']:
        args = ', '.join(c_type(p['type']) + ' ' + p['name'] for p in fn['parameters']) or 'void'
        header.append(f'uint32_t {fn["name"]}({args});')
        # The C records are declared below; move declarations after records.
        args = ', '.join(cs_type(p['type']) + ' ' + p['name'] for p in fn['parameters'])
        cs += [f'    [LibraryImport("arktrace_ffi", EntryPoint = "{fn["name"]}")]', '    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]', f'    public static partial uint {fn["name"]}({args});']
    declarations = header[-len(contract['functions']):]
    header = header[:-len(contract['functions'])]
    cs += ['}']
    sizes = {'u8': (1, 1), 'u32': (4, 4), 'u64': (8, 8), 'i64': (8, 8), 'f64': (8, 8)}
    layouts = []
    swift = ['// Generated by scripts/generate_ffi_bindings.py; do not edit.', 'import CArkTrace', 'enum GeneratedLayouts {', '    static func validate() {']
    probe = ['// Generated test-only projections; do not edit.', 'import CArkTrace', 'import Foundation']
    for record in contract['records']:
        name = record['name']
        out = wire if name in WIRE else rust
        derives = 'Clone, Copy, Debug, PartialEq' + (', Default' if all(not f['type'].endswith('*') for f in record['fields']) else '')
        header.append(f'typedef struct ArkTrace{name} {{')
        out += ['#[repr(C)]', f'#[derive({derives})]', f'pub struct {name} {{']
        cs += ['[StructLayout(LayoutKind.Sequential)]', f'public unsafe struct {name}', '{']
        offset, alignment, offsets = 0, 1, []
        for field in record['fields']:
            n, t = field['name'], field['type']
            out.append(f'    pub {n}: {rust_type(t)},')
            if '[' in t:
                base, count = t[:-1].split('[')
                header.append(f'    {c_type(base)} {n}[{count}];')
                cs.append(f'    public fixed {cs_type(base)} {n}[{count}];')
                size, align = sizes[base][0] * int(count), sizes[base][1]
            else:
                header.append(f'    {c_type(t)} {n};')
                cs.append(f'    public {cs_type(t)} {n};')
                size, align = (8, 8) if t.endswith('*') else sizes[t]
            offset = (offset + align - 1) // align * align
            offsets.append((n, offset))
            offset += size
            alignment = max(alignment, align)
        size = (offset + alignment - 1) // alignment * alignment
        sizes[name] = size, alignment
        header.append(f'}} ArkTrace{name};')
        out.append('}')
        cs.append('}')
        if 'Default' not in derives:
            out += [f'impl Default for {name} {{', '    fn default() -> Self {', '        Self {']
            for field in record['fields']:
                n, t = field['name'], field['type']
                default = 'std::ptr::null()' if t.startswith('const ') and t.endswith('*') else 'std::ptr::null_mut()' if t.endswith('*') else 'Default::default()'
                out.append(f'            {n}: {default},')
            out += ['        }', '    }', '}']
        header.append(f'ARKTRACE_LAYOUT_ASSERT(sizeof(ArkTrace{name}) == {size}, "{name} size");')
        out += ['#[cfg(target_pointer_width = "64")]', 'const _: () = {', f'    assert!(std::mem::size_of::<{name}>() == {size});', f'    assert!(std::mem::align_of::<{name}>() == {alignment});']
        for n, o in offsets:
            header.append(f'ARKTRACE_LAYOUT_ASSERT(offsetof(ArkTrace{name}, {n}) == {o}, "{name}.{n} offset");')
            out.append(f'    assert!(std::mem::offset_of!({name}, {n}) == {o});')
        out.append('};')
        layouts.append({'name': name, 'size': size, 'alignment': alignment, 'offsets': dict(offsets)})
        if name in WIRE:
            scalar = {'u8': 'UInt8', 'u32': 'UInt32', 'u64': 'UInt64', 'i64': 'Int64', 'f64': 'Double'}
            probe.append(f'struct Probe{name}: Codable, Sendable {{')
            for field in record['fields']:
                probe.append(f'    let {field["name"]}: {scalar[field["type"]]}')
            probe.append(f'    init(_ record: ArkTrace{name}) {{')
            for field in record['fields']:
                probe.append(f'        {field["name"]} = record.{field["name"]}')
            probe += ['    }', '}']
        swift += [f'        precondition(MemoryLayout<ArkTrace{name}>.size == {size})', f'        precondition(MemoryLayout<ArkTrace{name}>.alignment == {alignment})']
        for n, o in offsets:
            swift.append(f'        precondition(MemoryLayout<ArkTrace{name}>.offset(of: \\ArkTrace{name}.{n}) == {o})')
    header += declarations + ['#undef ARKTRACE_LAYOUT_ASSERT', '#ifdef __cplusplus', '}', '#endif', '#endif']
    swift += ['    }', '}']
    outputs = {ROOT / 'bindings/c/arktrace_ffi.h': '\n'.join(header)+'\n', ROOT / 'bindings/c/module.modulemap': 'module CArkTrace {\n    header "arktrace_ffi.h"\n    export *\n}\n', ROOT / 'bindings/csharp/NativeMethods.cs': '\n'.join(cs)+'\n', ROOT / 'bindings/ffi-layouts.json': json.dumps(layouts, indent=2)+'\n', ROOT / 'rust/crates/arktrace-ffi/src/abi_records.rs': '\n'.join(rust)+'\n', ROOT / 'rust/crates/arktrace-viewer/src/wire_records.rs': '\n'.join(wire)+'\n', ROOT / 'contracts/ffi-v1.sha256': digest+'\n'}
    outputs[ROOT / 'bindings/swift/GeneratedLayouts.swift'] = '\n'.join(swift)+'\n'
    outputs[ROOT / 'scripts/swift-sdk-conformance/GeneratedRecords.swift'] = '\n'.join(probe)+'\n'
    for p in outputs:
        if p.suffix == '.rs':
            outputs[p] = subprocess.run(['rustfmt', '+1.99.0', '--edition', '2024', '--emit', 'stdout'], input=outputs[p], text=True, capture_output=True, check=True).stdout
    for p, data in outputs.items():
        if '--check' in sys.argv:
            assert p.read_text() == data, p.relative_to(ROOT)
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(data)
    print(f'FFI v{contract["abiVersion"]}: {len(contract["records"])} records / {len(contract["functions"])} exports; digest {digest}')


if __name__ == '__main__':
    main()
