// Generated by scripts/generate_ffi_bindings.py; do not edit.
pub const WIRE_PRIMITIVE_DETAIL: u32 = 1;
pub const WIRE_PRIMITIVE_DENSITY: u32 = 2;
pub const WIRE_FLAG_VISIBLE: u32 = 1;
pub const WIRE_FLAG_FRAME: u32 = 2;
pub const WIRE_FLAG_OPEN_ENDED: u32 = 4;
pub const WIRE_FLAG_OCCUPANCY: u32 = 8;
pub const WIRE_FLAG_UTILIZATION: u32 = 16;
pub const WIRE_TRACK_COLLAPSED: u32 = 1;
pub const WIRE_TRACK_NESTED: u32 = 2;
pub const WIRE_TRACK_OWNER: u32 = 4;
pub const WIRE_QUALITY_SCOPE: u32 = 1;
pub const WIRE_QUALITY_COUNT: u32 = 2;
pub const WIRE_SOURCE_CPU: u32 = 1;
pub const WIRE_SOURCE_THREAD_STATE: u32 = 2;
pub const WIRE_SOURCE_NAMED_SLICE: u32 = 3;
pub const WIRE_SOURCE_CPU_COUNTER: u32 = 4;
pub const WIRE_SOURCE_PROCESS_COUNTER: u32 = 5;
pub const WIRE_SOURCE_FRAME: u32 = 6;
pub const WIRE_TABLE_SCHED_SLICE: u32 = 1;
pub const WIRE_TABLE_THREAD_STATE: u32 = 2;
pub const WIRE_TABLE_CALLSTACK: u32 = 3;
pub const WIRE_TABLE_MEASURE: u32 = 4;
pub const WIRE_TABLE_PROCESS_MEASURE: u32 = 5;
pub const WIRE_TABLE_FRAME_SLICE: u32 = 6;
pub const WIRE_STYLE_RUNNING: u32 = 1;
pub const WIRE_STYLE_RUNNABLE: u32 = 2;
pub const WIRE_STYLE_BLOCKED: u32 = 3;
pub const WIRE_STYLE_SLEEPING: u32 = 4;
pub const WIRE_STYLE_COUNTER: u32 = 5;
pub const WIRE_STYLE_ACCENT: u32 = 6;
pub const WIRE_DOMINANT_NAME: u32 = 2;
pub const WIRE_DOMINANT_THREAD_STATE: u32 = 3;
pub const WIRE_DOMINANT_JANK: u32 = 4;
pub const WIRE_QUALITY_PROBE_TRUNCATED: u32 = 1;
pub const WIRE_QUALITY_INVALID_VALUE: u32 = 2;
pub const WIRE_QUALITY_CLAMPED_VALUE: u32 = 3;
pub const WIRE_QUALITY_DROPPED_VALUE: u32 = 4;
pub const WIRE_QUALITY_REFERENTIAL_INTEGRITY: u32 = 5;
pub const WIRE_QUALITY_UNAVAILABLE_VALUE: u32 = 6;
pub const WIRE_QUALITY_UNCLASSIFIED: u32 = 7;
pub const WIRE_DOMINANT_IDENTITY: u32 = 1;
pub const WIRE_QUALITY_STATUS_OK: u32 = 1;
pub const WIRE_QUALITY_STATUS_WARNINGS: u32 = 2;
pub const WIRE_FLAG_RENDER_FACTS: u32 = 32;
pub const WIRE_FLAG_LABEL: u32 = 64;
pub const WIRE_FLAG_CATEGORY: u32 = 128;
pub const WIRE_FLAG_NAME: u32 = 256;
pub const WIRE_FLAG_PROCESS_NAME: u32 = 512;
pub const WIRE_FLAG_THREAD_NAME: u32 = 1024;
pub const WIRE_FLAG_INSPECTOR_CATEGORY: u32 = 2048;
pub const WIRE_FLAG_STATE: u32 = 4096;
pub const WIRE_FLAG_UNIT: u32 = 8192;
pub const WIRE_FLAG_SEMANTIC_DURATION: u32 = 16384;
pub const WIRE_FLAG_PROCESS_KEY: u32 = 32768;
pub const WIRE_FLAG_THREAD_KEY: u32 = 65536;
pub const WIRE_FLAG_PID: u32 = 131072;
pub const WIRE_FLAG_TID: u32 = 262144;
pub const WIRE_FLAG_CPU: u32 = 524288;
pub const WIRE_FLAG_VALUE: u32 = 1048576;
pub const WIRE_FLAG_PRIORITY: u32 = 2097152;
pub const WIRE_FLAG_COLOR: u32 = 4194304;
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct ViewportRecord {
    pub start_ns: i64,
    pub end_ns: i64,
    pub ns_per_point: f64,
    pub width_points: f64,
    pub height_points: f64,
    pub vertical_offset_points: f64,
    pub generation: u64,
    pub source_generation: u64,
    pub backing_scale: f64,
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<ViewportRecord>() == 72);
    assert!(std::mem::align_of::<ViewportRecord>() == 8);
    assert!(std::mem::offset_of!(ViewportRecord, start_ns) == 0);
    assert!(std::mem::offset_of!(ViewportRecord, end_ns) == 8);
    assert!(std::mem::offset_of!(ViewportRecord, ns_per_point) == 16);
    assert!(std::mem::offset_of!(ViewportRecord, width_points) == 24);
    assert!(std::mem::offset_of!(ViewportRecord, height_points) == 32);
    assert!(std::mem::offset_of!(ViewportRecord, vertical_offset_points) == 40);
    assert!(std::mem::offset_of!(ViewportRecord, generation) == 48);
    assert!(std::mem::offset_of!(ViewportRecord, source_generation) == 56);
    assert!(std::mem::offset_of!(ViewportRecord, backing_scale) == 64);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct TrackRecord {
    pub source_kind: u32,
    pub flags: u32,
    pub source_value: i64,
    pub filter_id: i64,
    pub owner_value: i64,
    pub id_offset: u32,
    pub id_length: u32,
    pub y: f64,
    pub height: f64,
    pub depth_rows: u32,
    pub primitive_start: u32,
    pub primitive_count: u32,
    pub reserved: u32,
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<TrackRecord>() == 72);
    assert!(std::mem::align_of::<TrackRecord>() == 8);
    assert!(std::mem::offset_of!(TrackRecord, source_kind) == 0);
    assert!(std::mem::offset_of!(TrackRecord, flags) == 4);
    assert!(std::mem::offset_of!(TrackRecord, source_value) == 8);
    assert!(std::mem::offset_of!(TrackRecord, filter_id) == 16);
    assert!(std::mem::offset_of!(TrackRecord, owner_value) == 24);
    assert!(std::mem::offset_of!(TrackRecord, id_offset) == 32);
    assert!(std::mem::offset_of!(TrackRecord, id_length) == 36);
    assert!(std::mem::offset_of!(TrackRecord, y) == 40);
    assert!(std::mem::offset_of!(TrackRecord, height) == 48);
    assert!(std::mem::offset_of!(TrackRecord, depth_rows) == 56);
    assert!(std::mem::offset_of!(TrackRecord, primitive_start) == 60);
    assert!(std::mem::offset_of!(TrackRecord, primitive_count) == 64);
    assert!(std::mem::offset_of!(TrackRecord, reserved) == 68);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct PrimitiveRecord {
    pub kind: u32,
    pub flags: u32,
    pub track_index: u32,
    pub event_table: u32,
    pub style: u32,
    pub reserved_header: u32,
    pub depth: i64,
    pub row_id: i64,
    pub start_ns: i64,
    pub end_ns: i64,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
    pub event_count: i64,
    pub occupied_ns: i64,
    pub utilization: f64,
    pub dominant_kind: u32,
    pub text_offset: u32,
    pub text_length: u32,
    pub reserved: u32,
    pub dominant_value: i64,
    pub event_kind: u32,
    pub color_rgb: u32,
    pub jank_tag: i64,
    pub semantic_duration_ns: i64,
    pub process_key: i64,
    pub thread_key: i64,
    pub pid: i64,
    pub tid: i64,
    pub cpu: i64,
    pub value: i64,
    pub priority: i64,
    pub label_offset: u32,
    pub label_length: u32,
    pub category_offset: u32,
    pub category_length: u32,
    pub name_offset: u32,
    pub name_length: u32,
    pub process_name_offset: u32,
    pub process_name_length: u32,
    pub thread_name_offset: u32,
    pub thread_name_length: u32,
    pub inspector_category_offset: u32,
    pub inspector_category_length: u32,
    pub state_offset: u32,
    pub state_length: u32,
    pub unit_offset: u32,
    pub unit_length: u32,
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<PrimitiveRecord>() == 280);
    assert!(std::mem::align_of::<PrimitiveRecord>() == 8);
    assert!(std::mem::offset_of!(PrimitiveRecord, kind) == 0);
    assert!(std::mem::offset_of!(PrimitiveRecord, flags) == 4);
    assert!(std::mem::offset_of!(PrimitiveRecord, track_index) == 8);
    assert!(std::mem::offset_of!(PrimitiveRecord, event_table) == 12);
    assert!(std::mem::offset_of!(PrimitiveRecord, style) == 16);
    assert!(std::mem::offset_of!(PrimitiveRecord, reserved_header) == 20);
    assert!(std::mem::offset_of!(PrimitiveRecord, depth) == 24);
    assert!(std::mem::offset_of!(PrimitiveRecord, row_id) == 32);
    assert!(std::mem::offset_of!(PrimitiveRecord, start_ns) == 40);
    assert!(std::mem::offset_of!(PrimitiveRecord, end_ns) == 48);
    assert!(std::mem::offset_of!(PrimitiveRecord, x) == 56);
    assert!(std::mem::offset_of!(PrimitiveRecord, y) == 64);
    assert!(std::mem::offset_of!(PrimitiveRecord, width) == 72);
    assert!(std::mem::offset_of!(PrimitiveRecord, height) == 80);
    assert!(std::mem::offset_of!(PrimitiveRecord, event_count) == 88);
    assert!(std::mem::offset_of!(PrimitiveRecord, occupied_ns) == 96);
    assert!(std::mem::offset_of!(PrimitiveRecord, utilization) == 104);
    assert!(std::mem::offset_of!(PrimitiveRecord, dominant_kind) == 112);
    assert!(std::mem::offset_of!(PrimitiveRecord, text_offset) == 116);
    assert!(std::mem::offset_of!(PrimitiveRecord, text_length) == 120);
    assert!(std::mem::offset_of!(PrimitiveRecord, reserved) == 124);
    assert!(std::mem::offset_of!(PrimitiveRecord, dominant_value) == 128);
    assert!(std::mem::offset_of!(PrimitiveRecord, event_kind) == 136);
    assert!(std::mem::offset_of!(PrimitiveRecord, color_rgb) == 140);
    assert!(std::mem::offset_of!(PrimitiveRecord, jank_tag) == 144);
    assert!(std::mem::offset_of!(PrimitiveRecord, semantic_duration_ns) == 152);
    assert!(std::mem::offset_of!(PrimitiveRecord, process_key) == 160);
    assert!(std::mem::offset_of!(PrimitiveRecord, thread_key) == 168);
    assert!(std::mem::offset_of!(PrimitiveRecord, pid) == 176);
    assert!(std::mem::offset_of!(PrimitiveRecord, tid) == 184);
    assert!(std::mem::offset_of!(PrimitiveRecord, cpu) == 192);
    assert!(std::mem::offset_of!(PrimitiveRecord, value) == 200);
    assert!(std::mem::offset_of!(PrimitiveRecord, priority) == 208);
    assert!(std::mem::offset_of!(PrimitiveRecord, label_offset) == 216);
    assert!(std::mem::offset_of!(PrimitiveRecord, label_length) == 220);
    assert!(std::mem::offset_of!(PrimitiveRecord, category_offset) == 224);
    assert!(std::mem::offset_of!(PrimitiveRecord, category_length) == 228);
    assert!(std::mem::offset_of!(PrimitiveRecord, name_offset) == 232);
    assert!(std::mem::offset_of!(PrimitiveRecord, name_length) == 236);
    assert!(std::mem::offset_of!(PrimitiveRecord, process_name_offset) == 240);
    assert!(std::mem::offset_of!(PrimitiveRecord, process_name_length) == 244);
    assert!(std::mem::offset_of!(PrimitiveRecord, thread_name_offset) == 248);
    assert!(std::mem::offset_of!(PrimitiveRecord, thread_name_length) == 252);
    assert!(std::mem::offset_of!(PrimitiveRecord, inspector_category_offset) == 256);
    assert!(std::mem::offset_of!(PrimitiveRecord, inspector_category_length) == 260);
    assert!(std::mem::offset_of!(PrimitiveRecord, state_offset) == 264);
    assert!(std::mem::offset_of!(PrimitiveRecord, state_length) == 268);
    assert!(std::mem::offset_of!(PrimitiveRecord, unit_offset) == 272);
    assert!(std::mem::offset_of!(PrimitiveRecord, unit_length) == 276);
};
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct QualityRecord {
    pub category: u32,
    pub flags: u32,
    pub scope_offset: u32,
    pub scope_length: u32,
    pub count: i64,
}
#[cfg(target_pointer_width = "64")]
const _: () = {
    assert!(std::mem::size_of::<QualityRecord>() == 24);
    assert!(std::mem::align_of::<QualityRecord>() == 8);
    assert!(std::mem::offset_of!(QualityRecord, category) == 0);
    assert!(std::mem::offset_of!(QualityRecord, flags) == 4);
    assert!(std::mem::offset_of!(QualityRecord, scope_offset) == 8);
    assert!(std::mem::offset_of!(QualityRecord, scope_length) == 12);
    assert!(std::mem::offset_of!(QualityRecord, count) == 16);
};
